"use client"

import * as React from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination"
import { ExternalLink, AlertCircle, CheckCircle2, Clock, ShieldAlert, Trash2, Eye } from "lucide-react"
import type { AutoGeneratedBlog, AutoGeneratedBlogStatus } from "./types"

interface AutoGeneratedTableProps {
  data: AutoGeneratedBlog[]
  selected: string[]
  onChangeSelected: (ids: string[]) => void
}

export function AutoGeneratedTable({ data, selected, onChangeSelected }: AutoGeneratedTableProps) {
  const [page, setPage] = React.useState(1)
  const [perPage, setPerPage] = React.useState(10)

  const totalPages = Math.ceil(data.length / perPage)
  const start = (page - 1) * perPage
  const end = start + perPage
  const visible = data.slice(start, end)

  const allVisibleSelected = visible.length > 0 && visible.every((b) => selected.includes(b.id))
  const someVisibleSelected = visible.some((b) => selected.includes(b.id)) && !allVisibleSelected

  function toggleAll() {
    if (allVisibleSelected) {
      onChangeSelected(selected.filter((id) => !visible.some((b) => b.id === id)))
    } else {
      const newIds = visible.map((b) => b.id).filter((id) => !selected.includes(id))
      onChangeSelected([...selected, ...newIds])
    }
  }

  function toggleRow(id: string) {
    onChangeSelected(selected.includes(id) ? selected.filter((x) => x !== id) : [...selected, id])
  }

  function getStatusBadge(status: AutoGeneratedBlogStatus) {
    switch (status) {
      case "success":
        return (
          <Badge variant="default" className="gap-1 bg-green-600">
            <CheckCircle2 className="h-3 w-3" />
            Success
          </Badge>
        )
      case "error":
        return (
          <Badge variant="destructive" className="gap-1">
            <AlertCircle className="h-3 w-3" />
            Error
          </Badge>
        )
      case "pending":
        return (
          <Badge variant="secondary" className="gap-1">
            <Clock className="h-3 w-3" />
            Pending
          </Badge>
        )
      case "quarantined":
        return (
          <Badge variant="outline" className="gap-1 border-yellow-600 text-yellow-600">
            <ShieldAlert className="h-3 w-3" />
            Quarantined
          </Badge>
        )
    }
  }

  function getPlatformBadge(platform: string) {
    const colors: Record<string, string> = {
      leetcode: "bg-orange-600",
      codechef: "bg-brown-600",
      hackerrank: "bg-green-700",
      codeforces: "bg-blue-600",
    }
    return (
      <Badge variant="secondary" className={colors[platform] || ""}>
        {platform}
      </Badge>
    )
  }

  const pageNumbers = React.useMemo(() => {
    const pages: (number | "ellipsis")[] = []
    if (totalPages <= 7) {
      for (let i = 1; i <= totalPages; i++) pages.push(i)
    } else {
      if (page <= 3) {
        pages.push(1, 2, 3, 4, "ellipsis", totalPages)
      } else if (page >= totalPages - 2) {
        pages.push(1, "ellipsis", totalPages - 3, totalPages - 2, totalPages - 1, totalPages)
      } else {
        pages.push(1, "ellipsis", page - 1, page, page + 1, "ellipsis", totalPages)
      }
    }
    return pages
  }, [page, totalPages])

  return (
    <div className="space-y-4">
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-12">
                <Checkbox
                  checked={allVisibleSelected}
                  onCheckedChange={toggleAll}
                  aria-label="Select all visible auto-generated blogs"
                  className={someVisibleSelected ? "data-[state=checked]:bg-muted" : ""}
                />
              </TableHead>
              <TableHead>Title</TableHead>
              <TableHead>Platform</TableHead>
              <TableHead>Author</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Created</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {visible.length === 0 ? (
              <TableRow>
                <TableCell colSpan={7} className="h-24 text-center text-muted-foreground">
                  No auto-generated blogs found.
                </TableCell>
              </TableRow>
            ) : (
              visible.map((blog) => (
                <TableRow key={blog.id}>
                  <TableCell>
                    <Checkbox
                      checked={selected.includes(blog.id)}
                      onCheckedChange={() => toggleRow(blog.id)}
                      aria-label={`Select ${blog.title}`}
                    />
                  </TableCell>
                  <TableCell className="font-medium">
                    <div className="max-w-md">
                      <div className="truncate">{blog.title}</div>
                      {blog.errorMessage && <div className="mt-1 text-xs text-destructive">{blog.errorMessage}</div>}
                    </div>
                  </TableCell>
                  <TableCell>{getPlatformBadge(blog.platform)}</TableCell>
                  <TableCell className="text-sm text-muted-foreground">{blog.author}</TableCell>
                  <TableCell>{getStatusBadge(blog.status)}</TableCell>
                  <TableCell className="text-sm text-muted-foreground">
                    {new Date(blog.createdAt).toLocaleDateString()}
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      {blog.blogUrl && (
                        <Button variant="ghost" size="sm" asChild>
                          <a href={blog.blogUrl} target="_blank" rel="noopener noreferrer">
                            <Eye className="h-4 w-4" />
                          </a>
                        </Button>
                      )}
                      <Button variant="ghost" size="sm" asChild>
                        <a href={blog.sourceUrl} target="_blank" rel="noopener noreferrer">
                          <ExternalLink className="h-4 w-4" />
                        </a>
                      </Button>
                      <Button variant="ghost" size="sm">
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>

      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-sm text-muted-foreground">Rows per page</span>
          <Select value={String(perPage)} onValueChange={(v) => setPerPage(Number(v))}>
            <SelectTrigger className="h-8 w-16">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="10">10</SelectItem>
              <SelectItem value="20">20</SelectItem>
              <SelectItem value="50">50</SelectItem>
              <SelectItem value="100">100</SelectItem>
            </SelectContent>
          </Select>
          <span className="text-sm text-muted-foreground">
            {start + 1}–{Math.min(end, data.length)} of {data.length}
          </span>
        </div>

        <Pagination>
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                aria-disabled={page === 1}
                className={page === 1 ? "pointer-events-none opacity-50" : "cursor-pointer"}
              />
            </PaginationItem>
            {pageNumbers.map((num, idx) =>
              num === "ellipsis" ? (
                <PaginationItem key={`ellipsis-${idx}`}>
                  <PaginationEllipsis />
                </PaginationItem>
              ) : (
                <PaginationItem key={num}>
                  <PaginationLink onClick={() => setPage(num)} isActive={page === num} className="cursor-pointer">
                    {num}
                  </PaginationLink>
                </PaginationItem>
              ),
            )}
            <PaginationItem>
              <PaginationNext
                onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                aria-disabled={page === totalPages}
                className={page === totalPages ? "pointer-events-none opacity-50" : "cursor-pointer"}
              />
            </PaginationItem>
          </PaginationContent>
        </Pagination>
      </div>
    </div>
  )
}
