import type { Blog } from "./types"

export const mockBlogs: Blog[] = [
  {
    id: "b1",
    title: "Understanding Dijkstra’s Algorithm",
    author: "Alice Johnson",
    status: "published",
    tags: ["algorithms", "graphs", "shortest-path"],
    language: "en",
    readTime: 8,
    publicationDate: "2024-08-12",
    views: 4821,
    commentsCount: 23,
    priority: "high",
  },
  {
    id: "b2",
    title: "Stacks vs Queues: Practical Use-Cases",
    author: "Bob Smith",
    status: "draft",
    tags: ["stacks", "queues", "data-structures"],
    language: "en",
    readTime: 6,
    priority: "medium",
  },
  {
    id: "b3",
    title: "Greedy Algorithms in Competitive Programming",
    author: "Carol Lee",
    status: "published",
    tags: ["algorithms", "greedy"],
    language: "en",
    readTime: 7,
    publicationDate: "2024-09-01",
    views: 2120,
    commentsCount: 12,
    priority: "low",
  },
  {
    id: "b4",
    title: "Dynamic Programming: Knapsack Patterns",
    author: "Alice Johnson",
    status: "scheduled",
    tags: ["dp", "patterns"],
    language: "en",
    readTime: 10,
    publicationDate: "2025-10-20",
    priority: "high",
  },
  {
    id: "b5",
    title: "Graph Traversals: BFS and DFS",
    author: "Diego Rivera",
    status: "published",
    tags: ["graphs", "bfs", "dfs"],
    language: "en",
    readTime: 9,
    publicationDate: "2024-07-10",
    views: 3560,
    commentsCount: 8,
    priority: "medium",
  },
  {
    id: "b6",
    title: "Concurrency Primitives in Rust",
    author: "Bob Smith",
    status: "draft",
    tags: ["rust", "concurrency"],
    language: "en",
    readTime: 11,
    priority: "low",
  },
  {
    id: "b7",
    title: "Union-Find: Disjoint Set Basics",
    author: "Carol Lee",
    status: "published",
    tags: ["data-structures", "union-find"],
    language: "en",
    readTime: 5,
    publicationDate: "2024-06-18",
    views: 1980,
    commentsCount: 5,
    priority: "medium",
  },
  {
    id: "b8",
    title: "Two-Pointer Techniques",
    author: "Evan Chen",
    status: "published",
    tags: ["arrays", "two-pointers"],
    language: "en",
    readTime: 4,
    publicationDate: "2024-10-02",
    views: 1250,
    commentsCount: 3,
    priority: "low",
  },
  {
    id: "b9",
    title: "Priority Queues and Heaps",
    author: "Diego Rivera",
    status: "scheduled",
    tags: ["heaps", "priority-queue"],
    language: "en",
    readTime: 7,
    publicationDate: "2025-11-14",
    priority: "high",
  },
  {
    id: "b10",
    title: "String Matching: KMP and Z-Algorithm",
    author: "Alice Johnson",
    status: "draft",
    tags: ["strings", "kmp", "z-algorithm"],
    language: "en",
    readTime: 12,
    priority: "medium",
  },
  {
    id: "b11",
    title: "Monotonic Stacks in Practice",
    author: "Bob Smith",
    status: "published",
    tags: ["stacks", "patterns", "monotonic"],
    language: "en",
    readTime: 6,
    publicationDate: "2024-05-22",
    views: 980,
    commentsCount: 2,
    priority: "low",
  },
  {
    id: "b12",
    title: "Segment Trees 101",
    author: "Evan Chen",
    status: "draft",
    tags: ["segment-tree", "data-structures"],
    language: "en",
    readTime: 13,
    priority: "high",
  },
]

export default mockBlogs
