export type BlogStatus = "draft" | "published" | "scheduled"

export type BlogPriority = "high" | "medium" | "low"

export type AutoGeneratedBlogStatus = "pending" | "success" | "error" | "quarantined"

export type Blog = {
  id: string
  title: string
  author: string
  status: BlogStatus
  tags: string[]
  language?: string
  readTime: number // minutes
  publicationDate?: string // ISO date for published/scheduled
  views?: number
  commentsCount?: number
  priority?: BlogPriority // priority for featured/editorial importance
}

export type AutoGeneratedBlog = {
  id: string
  title: string
  platform: "leetcode" | "codechef" | "hackerrank" | "codeforces"
  author: string
  status: AutoGeneratedBlogStatus
  createdAt: string
  errorMessage?: string
  blogUrl?: string // URL to the generated blog if successful
  sourceUrl: string // URL to the original problem/solution
}
