"use client"

import * as React from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
} from "@/components/ui/dropdown-menu"
import {
  ChevronDown,
  Filter,
  Plus,
  Search,
  Trash2,
  Upload,
  LayoutList,
  LayoutGrid,
  ArrowUpDown,
  AlertTriangle,
} from "lucide-react"
import { BlogsTable, BlogsCards } from "@/components/blogs/blogs-table"
import { AutoGeneratedTable } from "@/components/blogs/auto-generated-table"
import { mockBlogs } from "@/components/blogs/mock-data"
import { mockAutoGeneratedBlogs } from "@/components/blogs/auto-generated-mock-data"
import type { Blog, BlogStatus, AutoGeneratedBlog, AutoGeneratedBlogStatus } from "@/components/blogs/types"

export default function AdminDashboard({ section = "manual" }: { section?: "manual" | "auto-generated" }) {
  const [activeTab, setActiveTab] = React.useState("blogs")
  const [activeAutoTab, setActiveAutoTab] = React.useState("auto-blogs")

  return (
    <div className="space-y-6 p-6">
      <Header />

      {section === "manual" ? (
        <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
          <TabsList className="grid w-full max-w-3xl grid-cols-6">
            <TabsTrigger value="blogs">Blogs</TabsTrigger>
            <TabsTrigger value="authors">Authors</TabsTrigger>
            <TabsTrigger value="comments">Comments</TabsTrigger>
            <TabsTrigger value="tags">Tags</TabsTrigger>
            <TabsTrigger value="analytics">Analytics</TabsTrigger>
            <TabsTrigger value="recommendations">Feed</TabsTrigger>
          </TabsList>

          <TabsContent value="blogs" className="space-y-8">
            <BlogManager />
          </TabsContent>

          <TabsContent value="authors">
            <AuthorManagement />
          </TabsContent>

          <TabsContent value="comments">
            <CommentManagement />
          </TabsContent>

          <TabsContent value="tags">
            <TagManagement />
          </TabsContent>

          <TabsContent value="analytics">
            <AnalyticsInsights />
          </TabsContent>

          <TabsContent value="recommendations">
            <FeedRecommendations />
          </TabsContent>
        </Tabs>
      ) : (
        <Tabs value={activeAutoTab} onValueChange={setActiveAutoTab} className="space-y-6">
          <TabsList className="grid w-full max-w-3xl grid-cols-5">
            <TabsTrigger value="auto-blogs">Auto-Generated</TabsTrigger>
            <TabsTrigger value="platforms">Platforms</TabsTrigger>
            <TabsTrigger value="errors">Error Logs</TabsTrigger>
            <TabsTrigger value="history">Sync History</TabsTrigger>
            <TabsTrigger value="settings">Settings</TabsTrigger>
          </TabsList>

          
         

          <TabsContent value="platforms">
            <PlatformConfiguration />
          </TabsContent>

          <TabsContent value="errors">
            <ErrorLogs />
          </TabsContent>

          <TabsContent value="history">
            <SyncHistory />
          </TabsContent>

          <TabsContent value="settings">
            <AutoGenerationSettings />
          </TabsContent>
        </Tabs>
      )}
    </div>
  )
}

function Header() {
  return (
    <header>
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight text-balance">Admin Dashboard</h1>
          <p className="text-sm text-muted-foreground mt-1">Manage blogs, authors, comments, tags, and analytics.</p>
        </div>
      </div>
    </header>
  )
}

function PlatformConfiguration() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Platform Configuration</h3>
      <p className="text-sm text-muted-foreground mb-4">
        Configure auto-generation settings for LeetCode, CodeChef, HackerRank, and Codeforces
      </p>
      <Button>Configure Platforms</Button>
    </div>
  )
}

function ErrorLogs() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Error Logs</h3>
      <p className="text-sm text-muted-foreground mb-4">
        View detailed error logs, retry failed generations, and track resolution status
      </p>
      <Button>View Error Details</Button>
    </div>
  )
}

function SyncHistory() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Sync History</h3>
      <p className="text-sm text-muted-foreground mb-4">
        Track auto-generation runs, sync timestamps, and generation statistics
      </p>
      <Button>View Sync History</Button>
    </div>
  )
}

function AutoGenerationSettings() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Auto-Generation Settings</h3>
      <p className="text-sm text-muted-foreground mb-4">
        Configure auto-generation rules, scheduling, and default metadata
      </p>
      <Button>Edit Settings</Button>
    </div>
  )
}

function BlogManager() {
  const [query, setQuery] = React.useState("")
  const [status, setStatus] = React.useState<"all" | BlogStatus>("all")
  const [selectedTags, setSelectedTags] = React.useState<string[]>([])
  const [selectedAuthor, setSelectedAuthor] = React.useState<string | "all">("all")
  const [selected, setSelected] = React.useState<string[]>([])
  const [view, setView] = React.useState<"table" | "cards">("table")
  const [selectedPriorities, setSelectedPriorities] = React.useState<Array<"high" | "medium" | "low">>([])
  const [selectedLanguage, setSelectedLanguage] = React.useState<string | "all">("all")
  const [sortBy, setSortBy] = React.useState<"newest" | "oldest" | "mostViews" | "mostComments">("newest")

  const tags = React.useMemo(() => {
    const t = new Set<string>()
    mockBlogs.forEach((b) => b.tags.forEach((tag) => t.add(tag)))
    return Array.from(t).sort()
  }, [])

  const authors = React.useMemo(() => {
    const a = new Set<string>()
    mockBlogs.forEach((b) => a.add(b.author))
    return ["all", ...Array.from(a).sort()]
  }, [])

  const languages = React.useMemo(() => {
    const l = new Set<string>()
    mockBlogs.forEach((b) => b.language && l.add(b.language))
    return ["all", ...Array.from(l).sort()]
  }, [])

  const filtered: Blog[] = React.useMemo(() => {
    const base = mockBlogs
      .filter((b) => (status === "all" ? true : b.status === status))
      .filter((b) => (selectedAuthor === "all" ? true : b.author === selectedAuthor))
      .filter((b) => (selectedLanguage === "all" ? true : (b.language ?? "") === selectedLanguage))
      .filter((b) => (selectedTags.length ? selectedTags.every((t) => b.tags.includes(t)) : true))
      .filter((b) => {
        if (!query.trim()) return true
        const q = query.toLowerCase()
        return (
          b.title.toLowerCase().includes(q) ||
          b.author.toLowerCase().includes(q) ||
          b.tags.some((t) => t.toLowerCase().includes(q)) ||
          (b.language ?? "").toLowerCase().includes(q)
        )
      })
      .filter((b) =>
        selectedPriorities.length ? (b.priority ? selectedPriorities.includes(b.priority) : false) : true,
      )

    const copy = [...base]
    copy.sort((a, b) => {
      switch (sortBy) {
        case "newest": {
          const da = a.publicationDate ? new Date(a.publicationDate).getTime() : 0
          const db = b.publicationDate ? new Date(b.publicationDate).getTime() : 0
          return db - da
        }
        case "oldest": {
          const da = a.publicationDate ? new Date(a.publicationDate).getTime() : Number.MAX_SAFE_INTEGER
          const db = b.publicationDate ? new Date(b.publicationDate).getTime() : Number.MAX_SAFE_INTEGER
          return da - db
        }
        case "mostViews": {
          const va = typeof a.views === "number" ? a.views : 0
          const vb = typeof b.views === "number" ? b.views : 0
          return vb - va
        }
        case "mostComments": {
          const ca = typeof a.commentsCount === "number" ? a.commentsCount : 0
          const cb = typeof b.commentsCount === "number" ? b.commentsCount : 0
          return cb - ca
        }
        default:
          return 0
      }
    })
    return copy
  }, [query, status, selectedTags, selectedAuthor, selectedPriorities, selectedLanguage, sortBy])

  function toggleTag(tag: string) {
    setSelectedTags((prev) => (prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag]))
  }

  function clearFilters() {
    setQuery("")
    setStatus("all")
    setSelectedTags([])
    setSelectedAuthor("all")
    setSelectedPriorities([])
    setSelectedLanguage("all")
    setSortBy("newest")
  }

  function handleBulkDelete() {
    alert(`Bulk delete ${selected.length} item(s)`)
    setSelected([])
  }

  function handleBulkPublish() {
    alert(`Bulk publish ${selected.length} item(s)`)
    setSelected([])
  }

  return (
    <section className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold tracking-tight">Blog Management</h2>
          <p className="text-sm text-muted-foreground">Create, edit, and manage all blog posts</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline">
            <Upload className="mr-2 h-4 w-4" aria-hidden="true" />
            Import
          </Button>
          <Button>
            <Plus className="mr-2 h-4 w-4" aria-hidden="true" />
            New Blog
          </Button>
        </div>
      </div>

      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div className="flex flex-1 items-center gap-2">
          <div className="relative w-full max-w-sm">
            <Search
              className="pointer-events-none absolute left-2 top-2.5 h-4 w-4 text-muted-foreground"
              aria-hidden="true"
            />
            <Input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search blogs, authors, tags..."
              className="pl-8"
              aria-label="Search blogs, authors, or tags"
            />
          </div>

          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">
                <Filter className="mr-2 h-4 w-4" aria-hidden="true" />
                Filters
                <ChevronDown className="ml-2 h-4 w-4 opacity-70" aria-hidden="true" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" className="w-64">
              <DropdownMenuLabel>Status</DropdownMenuLabel>
              <div className="px-2 py-1">
                <DropdownMenuRadioGroup
                  value={status === "all" ? "all" : status}
                  onValueChange={(v) => setStatus(v as any)}
                >
                  <DropdownMenuRadioItem value="all">All</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="draft">Drafts</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="published">Published</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="scheduled">Scheduled</DropdownMenuRadioItem>
                </DropdownMenuRadioGroup>
              </div>
              <DropdownMenuSeparator />
              <DropdownMenuLabel>Author</DropdownMenuLabel>
              <div className="max-h-48 overflow-auto px-2 py-1">
                {authors.map((a) => (
                  <DropdownMenuCheckboxItem
                    key={a}
                    checked={selectedAuthor === a}
                    onCheckedChange={() => setSelectedAuthor(a)}
                  >
                    {a === "all" ? "All authors" : a}
                  </DropdownMenuCheckboxItem>
                ))}
              </div>
              <DropdownMenuSeparator />
              <DropdownMenuLabel>Tags</DropdownMenuLabel>
              <div className="max-h-56 space-y-1 overflow-auto px-2 py-2">
                {tags.map((t) => (
                  <DropdownMenuCheckboxItem
                    key={t}
                    checked={selectedTags.includes(t)}
                    onCheckedChange={() => toggleTag(t)}
                  >
                    {t}
                  </DropdownMenuCheckboxItem>
                ))}
              </div>
              <DropdownMenuSeparator />
              <DropdownMenuLabel>Priority</DropdownMenuLabel>
              <div className="max-h-40 space-y-1 overflow-auto px-2 py-2">
                {(["high", "medium", "low"] as const).map((p) => (
                  <DropdownMenuCheckboxItem
                    key={p}
                    checked={selectedPriorities.includes(p)}
                    onCheckedChange={() =>
                      setSelectedPriorities((prev) => (prev.includes(p) ? prev.filter((x) => x !== p) : [...prev, p]))
                    }
                    className="capitalize"
                  >
                    {p}
                  </DropdownMenuCheckboxItem>
                ))}
              </div>
              <DropdownMenuSeparator />
              <DropdownMenuLabel>Language</DropdownMenuLabel>
              <div className="max-h-40 space-y-1 overflow-auto px-2 py-2">
                {languages.map((lng) => (
                  <DropdownMenuCheckboxItem
                    key={lng}
                    checked={selectedLanguage === lng}
                    onCheckedChange={() => setSelectedLanguage(lng)}
                    className="capitalize"
                  >
                    {lng === "all" ? "All languages" : lng}
                  </DropdownMenuCheckboxItem>
                ))}
              </div>
            </DropdownMenuContent>
          </DropdownMenu>

          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">
                <ArrowUpDown className="mr-2 h-4 w-4" aria-hidden="true" />
                Sort
                <ChevronDown className="ml-2 h-4 w-4 opacity-70" aria-hidden="true" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" className="w-48">
              <DropdownMenuCheckboxItem checked={sortBy === "newest"} onCheckedChange={() => setSortBy("newest")}>
                Newest
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem checked={sortBy === "oldest"} onCheckedChange={() => setSortBy("oldest")}>
                Oldest
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem checked={sortBy === "mostViews"} onCheckedChange={() => setSortBy("mostViews")}>
                Most views
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={sortBy === "mostComments"}
                onCheckedChange={() => setSortBy("mostComments")}
              >
                Most comments
              </DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>

          {(status !== "all" ||
            selectedTags.length ||
            selectedAuthor !== "all" ||
            query ||
            selectedPriorities.length ||
            selectedLanguage !== "all" ||
            sortBy !== "newest") && (
            <Button variant="ghost" onClick={clearFilters}>
              Clear filters
            </Button>
          )}
        </div>

        <div className="flex items-center gap-2">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">
                {view === "table" ? <LayoutList className="mr-2 h-4 w-4" /> : <LayoutGrid className="mr-2 h-4 w-4" />}
                View
                <ChevronDown className="ml-2 h-4 w-4 opacity-70" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-40">
              <DropdownMenuCheckboxItem checked={view === "table"} onCheckedChange={() => setView("table")}>
                <LayoutList className="mr-2 h-4 w-4" />
                Table
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem checked={view === "cards"} onCheckedChange={() => setView("cards")}>
                <LayoutGrid className="mr-2 h-4 w-4" />
                Cards
              </DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>

          <Button variant="outline" disabled={!selected.length} onClick={handleBulkPublish}>
            Publish selected
          </Button>
          <Button variant="destructive" disabled={!selected.length} onClick={handleBulkDelete}>
            <Trash2 className="mr-2 h-4 w-4" aria-hidden="true" />
            Delete selected
          </Button>
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        {status !== "all" && <Badge variant="secondary">Status: {status}</Badge>}
        {selectedAuthor !== "all" && <Badge variant="secondary">Author: {selectedAuthor}</Badge>}
        {selectedLanguage !== "all" && <Badge variant="secondary">Language: {selectedLanguage}</Badge>}
        {selectedTags.map((t) => (
          <Badge key={t} variant="secondary" className="capitalize">
            {t}
          </Badge>
        ))}
        {query && <Badge variant="secondary">Query: {query}</Badge>}
        {selectedPriorities.map((p) => (
          <Badge key={p} variant="secondary" className="capitalize">
            Priority: {p}
          </Badge>
        ))}
        {sortBy !== "newest" && (
          <Badge variant="secondary" className="capitalize">
            Sort: {sortBy}
          </Badge>
        )}
      </div>

      {view === "table" ? (
        <BlogsTable data={filtered} selected={selected} onChangeSelected={setSelected} />
      ) : (
        <BlogsCards data={filtered} />
      )}
    </section>
  )
}

function AuthorManagement() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Author Management</h3>
      <p className="text-sm text-muted-foreground mb-4">
        Add/remove authors, view stats, assign roles (Admin, Editor, Contributor)
      </p>
      <Button>Add Author</Button>
    </div>
  )
}

function CommentManagement() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Comment Management</h3>
      <p className="text-sm text-muted-foreground mb-4">
        Flag/delete comments, quarantine inappropriate content, manage user warnings
      </p>
      <Button>View Flagged Comments</Button>
    </div>
  )
}

function TagManagement() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Tag & Category Management</h3>
      <p className="text-sm text-muted-foreground mb-4">
        Add, merge, update, or delete tags. Implement sub-tags and tree view
      </p>
      <Button>Manage Tags</Button>
    </div>
  )
}

function AnalyticsInsights() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Analytics & Insights</h3>
      <p className="text-sm text-muted-foreground mb-4">
        Blog performance (views, likes, shares), user engagement metrics, top commenters
      </p>
      <Button>View Analytics</Button>
    </div>
  )
}

function FeedRecommendations() {
  return (
    <div className="rounded-lg border p-8 text-center">
      <h3 className="text-lg font-semibold mb-2">Feed Recommendations</h3>
      <p className="text-sm text-muted-foreground mb-4">
        Manually assign 10-20 articles for the feed and related article recommendations
      </p>
      <Button>Manage Feed</Button>
    </div>
  )
}
