"use client"

import * as React from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
} from "@/components/ui/dropdown-menu"
import { ChevronDown, Filter, Search, Trash2, AlertTriangle, RefreshCw, Tag, Zap } from "lucide-react"
import { AutoGeneratedTable } from "@/components/blogs/auto-generated-table"
import { mockAutoGeneratedBlogs } from "@/components/blogs/auto-generated-mock-data"
import type { AutoGeneratedBlog, AutoGeneratedBlogStatus } from "@/components/blogs/types"

export default function AutoGeneratedDashboard() {
  const [activeTab, setActiveTab] = React.useState("auto-blogs")

  return (
    <div className="space-y-6 p-6">
      <Header />

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <TabsList className="grid w-full max-w-4xl grid-cols-7">
          <TabsTrigger value="auto-blogs">Auto-Generated</TabsTrigger>
          <TabsTrigger value="platforms">Platforms</TabsTrigger>
          <TabsTrigger value="tags">Tags</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
          <TabsTrigger value="feed">Feed</TabsTrigger>
          <TabsTrigger value="errors">Errors</TabsTrigger>
          <TabsTrigger value="history">History</TabsTrigger>
        </TabsList>

        <TabsContent value="auto-blogs" className="space-y-8">
          <AutoGeneratedBlogManager />
        </TabsContent>

        <TabsContent value="platforms">
          <PlatformConfiguration />
        </TabsContent>

        <TabsContent value="tags">
          <TagManagement />
        </TabsContent>

        <TabsContent value="analytics">
          <AnalyticsSection />
        </TabsContent>

        <TabsContent value="feed">
          <FeedManagement />
        </TabsContent>

        <TabsContent value="errors">
          <ErrorLogs />
        </TabsContent>

        <TabsContent value="history">
          <SyncHistory />
        </TabsContent>
      </Tabs>
    </div>
  )
}

function Header() {
  return (
    <header>
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight text-balance">Auto-Generated Blogs</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Monitor and manage blogs automatically generated from coding platforms.
          </p>
        </div>
      </div>
    </header>
  )
}

function AutoGeneratedBlogManager() {
  const [query, setQuery] = React.useState("")
  const [status, setStatus] = React.useState<"all" | AutoGeneratedBlogStatus>("all")
  const [selectedPlatform, setSelectedPlatform] = React.useState<string | "all">("all")
  const [selected, setSelected] = React.useState<string[]>([])

  const platforms = React.useMemo(() => {
    const p = new Set<string>()
    mockAutoGeneratedBlogs.forEach((b) => p.add(b.platform))
    return ["all", ...Array.from(p).sort()]
  }, [])

  const filtered: AutoGeneratedBlog[] = React.useMemo(() => {
    return mockAutoGeneratedBlogs
      .filter((b) => (status === "all" ? true : b.status === status))
      .filter((b) => (selectedPlatform === "all" ? true : b.platform === selectedPlatform))
      .filter((b) => {
        if (!query.trim()) return true
        const q = query.toLowerCase()
        return (
          b.title.toLowerCase().includes(q) ||
          b.author.toLowerCase().includes(q) ||
          b.platform.toLowerCase().includes(q)
        )
      })
  }, [query, status, selectedPlatform])

  function clearFilters() {
    setQuery("")
    setStatus("all")
    setSelectedPlatform("all")
  }

  function handleBulkDelete() {
    alert(`Bulk delete ${selected.length} auto-generated blog(s)`)
    setSelected([])
  }

  function handleBulkRetry() {
    alert(`Retrying ${selected.length} failed blog(s)`)
    setSelected([])
  }

  const errorCount = mockAutoGeneratedBlogs.filter((b) => b.status === "error").length
  const pendingCount = mockAutoGeneratedBlogs.filter((b) => b.status === "pending").length

  return (
    <section className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold tracking-tight">Blog Generation Status</h2>
          <p className="text-sm text-muted-foreground">
            Monitor blogs from LeetCode, CodeChef, HackerRank, and Codeforces
          </p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        <div className="rounded-lg border p-4">
          <div className="text-sm text-muted-foreground">Total Generated</div>
          <div className="text-2xl font-semibold mt-1">{mockAutoGeneratedBlogs.length}</div>
        </div>
        <div className="rounded-lg border p-4">
          <div className="text-sm text-muted-foreground">Pending</div>
          <div className="text-2xl font-semibold mt-1 text-yellow-600">{pendingCount}</div>
        </div>
        <div className="rounded-lg border p-4">
          <div className="text-sm text-muted-foreground">Errors</div>
          <div className="text-2xl font-semibold mt-1 text-destructive">{errorCount}</div>
        </div>
      </div>

      {errorCount > 0 && (
        <div className="flex items-center gap-2 rounded-md border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive">
          <AlertTriangle className="h-4 w-4" />
          <span>
            {errorCount} blog{errorCount > 1 ? "s" : ""} failed to generate. Review errors and retry.
          </span>
        </div>
      )}

      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div className="flex flex-1 items-center gap-2">
          <div className="relative w-full max-w-sm">
            <Search
              className="pointer-events-none absolute left-2 top-2.5 h-4 w-4 text-muted-foreground"
              aria-hidden="true"
            />
            <Input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search by title, author, platform..."
              className="pl-8"
              aria-label="Search auto-generated blogs"
            />
          </div>

          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">
                <Filter className="mr-2 h-4 w-4" aria-hidden="true" />
                Filters
                <ChevronDown className="ml-2 h-4 w-4 opacity-70" aria-hidden="true" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" className="w-64">
              <DropdownMenuLabel>Status</DropdownMenuLabel>
              <div className="px-2 py-1">
                <DropdownMenuRadioGroup
                  value={status === "all" ? "all" : status}
                  onValueChange={(v) => setStatus(v as any)}
                >
                  <DropdownMenuRadioItem value="all">All</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="success">Success</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="error">Error</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="pending">Pending</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="quarantined">Quarantined</DropdownMenuRadioItem>
                </DropdownMenuRadioGroup>
              </div>
              <DropdownMenuSeparator />
              <DropdownMenuLabel>Platform</DropdownMenuLabel>
              <div className="max-h-48 overflow-auto px-2 py-1">
                {platforms.map((p) => (
                  <DropdownMenuCheckboxItem
                    key={p}
                    checked={selectedPlatform === p}
                    onCheckedChange={() => setSelectedPlatform(p)}
                    className="capitalize"
                  >
                    {p === "all" ? "All platforms" : p}
                  </DropdownMenuCheckboxItem>
                ))}
              </div>
            </DropdownMenuContent>
          </DropdownMenu>

          {(status !== "all" || selectedPlatform !== "all" || query) && (
            <Button variant="ghost" onClick={clearFilters}>
              Clear filters
            </Button>
          )}
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" disabled={!selected.length} onClick={handleBulkRetry}>
            <RefreshCw className="mr-2 h-4 w-4" aria-hidden="true" />
            Retry selected
          </Button>
          <Button variant="destructive" disabled={!selected.length} onClick={handleBulkDelete}>
            <Trash2 className="mr-2 h-4 w-4" aria-hidden="true" />
            Delete selected
          </Button>
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        {status !== "all" && (
          <Badge variant="secondary" className="capitalize">
            Status: {status}
          </Badge>
        )}
        {selectedPlatform !== "all" && (
          <Badge variant="secondary" className="capitalize">
            Platform: {selectedPlatform}
          </Badge>
        )}
        {query && <Badge variant="secondary">Query: {query}</Badge>}
      </div>

      <AutoGeneratedTable data={filtered} selected={selected} onChangeSelected={setSelected} />
    </section>
  )
}

function PlatformConfiguration() {
  const platforms = [
    { name: "LeetCode", status: "Connected", lastSync: "2 hours ago" },
    { name: "CodeChef", status: "Connected", lastSync: "1 hour ago" },
    { name: "HackerRank", status: "Disconnected", lastSync: "Never" },
    { name: "Codeforces", status: "Connected", lastSync: "30 minutes ago" },
  ]

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-xl font-semibold tracking-tight">Platform Configuration</h2>
        <p className="text-sm text-muted-foreground">Configure auto-generation settings for each coding platform</p>
      </div>

      <div className="space-y-3">
        {platforms.map((p) => (
          <div key={p.name} className="flex items-center justify-between rounded-lg border p-4">
            <div>
              <h3 className="font-medium">{p.name}</h3>
              <p className="text-sm text-muted-foreground">Last sync: {p.lastSync}</p>
            </div>
            <div className="flex items-center gap-3">
              <Badge variant={p.status === "Connected" ? "default" : "secondary"}>{p.status}</Badge>
              <Button variant="outline" size="sm">
                Configure
              </Button>
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}

function TagManagement() {
  const [tags, setTags] = React.useState([
    { id: "1", name: "algorithms", count: 12, color: "bg-blue-100 text-blue-800" },
    { id: "2", name: "data-structures", count: 8, color: "bg-purple-100 text-purple-800" },
    { id: "3", name: "dynamic-programming", count: 5, color: "bg-green-100 text-green-800" },
    { id: "4", name: "graph-theory", count: 3, color: "bg-orange-100 text-orange-800" },
  ])
  const [newTag, setNewTag] = React.useState("")

  function handleAddTag() {
    if (newTag.trim()) {
      setTags([...tags, { id: Date.now().toString(), name: newTag, count: 0, color: "bg-gray-100 text-gray-800" }])
      setNewTag("")
    }
  }

  function handleDeleteTag(id: string) {
    setTags(tags.filter((t) => t.id !== id))
  }

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-xl font-semibold tracking-tight">Tag Management</h2>
        <p className="text-sm text-muted-foreground">Organize and categorize auto-generated blogs with tags</p>
      </div>

      <div className="flex gap-2">
        <Input
          value={newTag}
          onChange={(e) => setNewTag(e.target.value)}
          placeholder="Add new tag..."
          onKeyPress={(e) => e.key === "Enter" && handleAddTag()}
        />
        <Button onClick={handleAddTag}>
          <Tag className="mr-2 h-4 w-4" />
          Add Tag
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        {tags.map((tag) => (
          <div key={tag.id} className="flex items-center justify-between rounded-lg border p-4">
            <div className="flex items-center gap-3">
              <Badge className={tag.color}>{tag.name}</Badge>
              <span className="text-sm text-muted-foreground">{tag.count} blogs</span>
            </div>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => handleDeleteTag(tag.id)}
              className="text-destructive hover:text-destructive"
            >
              <Trash2 className="h-4 w-4" />
            </Button>
          </div>
        ))}
      </div>
    </section>
  )
}

function AnalyticsSection() {
  const analytics = [
    { platform: "LeetCode", totalBlogs: 45, successRate: "95%", avgViews: 1250, avgEngagement: "8.5%" },
    { platform: "CodeChef", totalBlogs: 28, successRate: "89%", avgViews: 890, avgEngagement: "6.2%" },
    { platform: "HackerRank", totalBlogs: 15, successRate: "87%", avgViews: 650, avgEngagement: "5.1%" },
    { platform: "Codeforces", totalBlogs: 32, successRate: "92%", avgViews: 1100, avgEngagement: "7.8%" },
  ]

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-xl font-semibold tracking-tight">Analytics & Performance</h2>
        <p className="text-sm text-muted-foreground">View performance metrics for auto-generated blogs by platform</p>
      </div>

      <div className="space-y-3">
        {analytics.map((stat) => (
          <div key={stat.platform} className="rounded-lg border p-4">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-medium">{stat.platform}</h3>
              <Badge variant="outline">{stat.successRate} Success Rate</Badge>
            </div>
            <div className="grid grid-cols-3 gap-4">
              <div>
                <p className="text-xs text-muted-foreground">Total Blogs</p>
                <p className="text-lg font-semibold">{stat.totalBlogs}</p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Avg Views</p>
                <p className="text-lg font-semibold">{stat.avgViews.toLocaleString()}</p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Avg Engagement</p>
                <p className="text-lg font-semibold">{stat.avgEngagement}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}

function FeedManagement() {
  const [feedBlogs, setFeedBlogs] = React.useState([
    { id: "auto-1", title: "Two Sum - LeetCode Solution", platform: "LeetCode", featured: true },
    { id: "auto-3", title: "Maximum Subarray - Kadane's Algorithm", platform: "LeetCode", featured: true },
    { id: "auto-5", title: "Merge Intervals Problem", platform: "LeetCode", featured: false },
  ])

  function toggleFeatured(id: string) {
    setFeedBlogs(feedBlogs.map((b) => (b.id === id ? { ...b, featured: !b.featured } : b)))
  }

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-xl font-semibold tracking-tight">Feed Management</h2>
        <p className="text-sm text-muted-foreground">Assign auto-generated blogs to the main feed</p>
      </div>

      <div className="rounded-lg border p-4 bg-blue-50 text-blue-900 text-sm">
        <p>
          <strong>Tip:</strong> Featured blogs will appear prominently in the main feed. You can feature up to 10 blogs
          at a time.
        </p>
      </div>

      <div className="space-y-2">
        {feedBlogs.map((blog) => (
          <div key={blog.id} className="flex items-center justify-between rounded-lg border p-4">
            <div>
              <h3 className="font-medium">{blog.title}</h3>
              <p className="text-sm text-muted-foreground">{blog.platform}</p>
            </div>
            <Button variant={blog.featured ? "default" : "outline"} size="sm" onClick={() => toggleFeatured(blog.id)}>
              <Zap className="mr-2 h-4 w-4" />
              {blog.featured ? "Featured" : "Feature"}
            </Button>
          </div>
        ))}
      </div>
    </section>
  )
}

function ErrorLogs() {
  const errors = mockAutoGeneratedBlogs.filter((b) => b.status === "error")

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-xl font-semibold tracking-tight">Error Logs</h2>
        <p className="text-sm text-muted-foreground">View detailed error logs and retry failed generations</p>
      </div>

      {errors.length === 0 ? (
        <div className="rounded-lg border p-8 text-center">
          <p className="text-muted-foreground">No errors found. All blogs generated successfully!</p>
        </div>
      ) : (
        <div className="space-y-3">
          {errors.map((error) => (
            <div key={error.id} className="rounded-lg border border-destructive/50 bg-destructive/5 p-4">
              <div className="flex items-start justify-between">
                <div>
                  <h3 className="font-medium">{error.title}</h3>
                  <p className="text-sm text-destructive mt-1">{error.errorMessage}</p>
                  <p className="text-xs text-muted-foreground mt-2">
                    {error.platform} • {new Date(error.createdAt).toLocaleString()}
                  </p>
                </div>
                <Button variant="outline" size="sm">
                  Retry
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  )
}

function SyncHistory() {
  const syncRuns = [
    { date: "2025-01-15", time: "10:30 AM", platform: "LeetCode", status: "Success", count: 5 },
    { date: "2025-01-15", time: "09:15 AM", platform: "CodeChef", status: "Success", count: 3 },
    { date: "2025-01-14", time: "02:00 PM", platform: "LeetCode", status: "Partial", count: "4/5" },
    { date: "2025-01-14", time: "11:45 AM", platform: "HackerRank", status: "Failed", count: 0 },
  ]

  return (
    <section className="space-y-4">
      <div>
        <h2 className="text-xl font-semibold tracking-tight">Sync History</h2>
        <p className="text-sm text-muted-foreground">Track auto-generation runs and sync statistics</p>
      </div>

      <div className="space-y-2">
        {syncRuns.map((run, idx) => (
          <div key={idx} className="flex items-center justify-between rounded-lg border p-4">
            <div>
              <p className="font-medium">{run.platform}</p>
              <p className="text-sm text-muted-foreground">
                {run.date} at {run.time}
              </p>
            </div>
            <div className="flex items-center gap-4">
              <div className="text-right">
                <p className="text-sm font-medium">{run.count} blogs</p>
                <Badge variant={run.status === "Success" ? "default" : "secondary"}>{run.status}</Badge>
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}
